http:
  middlewares:
    authelia:
      forwardAuth:
        address: "http://authelia_app:9091/api/verify?rd=https://auth.adam-ant.co.uk"
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email
