version: '2.0'

services:
  imageinfo:
    image: spritsail/image-info
    container_name: image-info
    restart: unless-stopped
    networks:
      - nginx_proxy

networks:
  nginx_proxy:
    external: true
