version: '2.4'

services:
  homeserver:
    image: matrixconduit/matrix-conduit:latest
    user: root
    volumes:
      - /volumes/matrix/config.toml:/etc/conduit/config.toml:ro
      - /volumes/matrix/database:/var/lib/matrix-conduit/
    networks:
      - nginx_proxy
    environment:
      CONDUIT_CONFIG: /etc/conduit/config.toml
    restart: unless-stopped

  maubot:
    image: dock.mau.dev/maubot/maubot
    volumes:
      - /volumes/matrix/maubot:/data:z
    networks:
      - nginx_proxy
    restart: on-failure

networks:
  nginx_proxy:
    external: true
