providers:
  docker:
    watch: true
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
    swarmMode: true
    network: network_public

  file:
    watch: true
    directory: /etc/traefik/configs

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"
    http:
      tls: {}


log:
  level: DEBUG

accessLog:
  filePath: "/etc/traefik/access.log"

api:
  dashboard: true
  insecure: true
