providers:
  swarm:
    watch: true
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
    network: network_public

  file:
    watch: true
    directory: /etc/traefik/configs

certificatesResolvers:
  letsencrypt:
    acme:
      dnsChallenge:
        provider: cloudflare
      email: {{ email }}
      storage: "/etc/traefik/acme.json"

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: "{{ domain }}"
            sans:
              - "*.{{ domain }}"


log:
  level: INFO

accessLog:
  filePath: "/etc/traefik/access.log"

api:
  dashboard: true
  insecure: true
