version: "3.9"

services:
  bitwarden:
    image: vaultwarden/server:latest
    volumes:
      - /volumes/bitwarden:/data
    deploy:
      restart_policy:
        delay: 10s
        window: 10s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.bitwarden.rule=Host(`bitwarden.adam-ant.co.uk`)"
        - "traefik.http.services.bitwarden.loadbalancer.server.port=80"
        - "traefik.http.routers.bitwarden.service=bitwarden"
        - "traefik.http.routers.bitwarden-websocket.rule=Host(`bitwarden.adam-ant.co.uk`) && Path(`/notifications/hub`)"
        - "traefik.http.routers.bitwarden-websocket.service=bitwarden-websocket"
        - "traefik.http.services.bitwarden-websocket.loadbalancer.server.port=3012"
    environment:
      WEBSOCKET_ENABLED: 'true'
      SIGNUPS_ALLOWED: 'false'
      INVITATIONS_ALLOWED: 'true'
      #ADMIN_TOKEN: 'TokenToEnableAdminPanel'
      DOMAIN: 'https://bitwarden.adam-ant.co.uk'
      SHOW_PASSWORD_HINT: 'false'

networks:
  default:
    name: network_public
    external: true
