version: "3.9"

services:
  bitwarden:
    image: vaultwarden/server:latest
    volumes:
      - /volumes/bitwarden:/data
    deploy:
      restart_policy:
        delay: 10s
        window: 10s
      label:
        - "traefik.enable=true"
        - "traefik.http.routers.bitwarden.rule=Host(`bitwarden.adam-ant.co.uk`)"
    environment:
      WEBSOCKET_ENABLED: 'true'
      SIGNUPS_ALLOWED: 'false'
      INVITATIONS_ALLOWED: 'true'
      #ADMIN_TOKEN: 'TokenToEnableAdminPanel'
      DOMAIN: 'https://bitwarden.adam-ant.co.uk'
      SHOW_PASSWORD_HINT: 'false'

networks:
  default:
    name: network_public
    external: true
