version: "2.0"

services:
  creative:
    image: spritsail/minecraft:latest
    container_name: minecraft-creative
    restart: unless-stopped
    volumes:
      - /volumes/minecraft-creative:/mc:rw
    ports:
      - 25502:25565
    environment:
      - INIT_MEM=512M
      - MAX_MEM=4G
      - SERVER_JAR=/mc/paper.jar

