version: '3.9'

services:

  organizr:
    image: organizr/organizr
    volumes:
      - /volumes/media/organizr:/config
    environment:
      - "branch=v2-master"
      - "PUID=971"
      - "PGID=971"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.organizr.rule=Host(`media.adam-ant.co.uk`)"
        - "traefik.http.services.organizr.loadbalancer.server.port=80"

    networks:
      - nginx_frontend

  nzbget:
    image: spritsail/nzbget
    volumes:
      - /volumes/media/nzbget:/config
      - /mnt/media:/media
    environment:
      - "SUID=901"
      - "GUID=901"
    networks:
      - nginx_frontend

  prowlarr:
    image: spritsail/prowlarr
    volumes:
      - /volumes/media/prowlarr:/config
    environment:
      - "SUID=911"
      - "GUID=911"
    networks:
      - nginx_frontend

  sonarr:
    image: spritsail/sonarr
    volumes:
      - /volumes/media/sonarr:/config
      - /mnt/media:/media
    environment:
      - "SUID=921"
      - "GUID=921"
    networks:
      - nginx_frontend

  radarr:
    image: spritsail/radarr
    volumes:
      - /volumes/media/radarr:/config
      - /mnt/media:/media
    environment:
      - "URL_BASE=/radarr"
      - "SUID=922"
      - "GUID=922"
    networks:
      - nginx_frontend

  lidarr:
    image: spritsail/lidarr
    volumes:
      - /volumes/media/lidarr:/config
      - /mnt/media:/media
    environment:
      - "SUID=923"
      - "GUID=923"
    networks:
      - nginx_frontend

  tautulli:
    image: spritsail/tautulli
    volumes:
      - /volumes/media/tautulli:/config
    environment:
      - "SUID=951"
      - "GUID=951"
    networks:
      - nginx_frontend

#    plex:
#      image: spritsail/plex-media-server:plexpass
#      volumes:
#        - /volumes/media/plex:/config
#        - /mnt/media:/media
#      ports:
#        - "1900:1900/udp"
#        - "3005:3005"
#        - "5353:5353/udp"
#        - "8324:8324"
#        - "32400:32400"
#        - "32410:32410/udp"
#        - "32412-32414:32412-32414/udp"
#        - "32469:32469"
#      networks:
#        - nginx_frontend
#
#    jellyfin:
#      image: jellyfin/jellyfin:latest
#      volumes:
#        - /volumes/media/jellyfin/config:/config
#        - /volumes/media/jellyfin/cache:/cache
#        - /mnt/media:/media
#      ports:
#        - "1900:1900"
#        - "7359:7359/udp"
#      networks:
#        - nginx_frontend

networks:
  nginx_frontend:
    external: true
