version: '3.9'
services:

  homeassistant:
    image: homeassistant/home-assistant
    volumes:
      - /volumes/ha/hass/:/config
      - /mnt/media/:/mnt/media
    environment:
      - TZ=Europe/London
    deploy:
      restart_policy:
        delay: 10s
        window: 10s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.homeassistant.rule=Host(`ha.adam-ant.co.uk`)"
        - "traefik.http.services.homeassistant.server.port=8123"
    networks:
      - default
      - network_public

  zigbee2mqtt:
    environment:
      - TZ=Europe/London
    image: koenkk/zigbee2mqtt
    deploy:
      restart_policy:
        delay: 10s
        window: 10s
    ports:
      - 8080:8080
    volumes:
      - /volumes/ha/zigbee/:/app/data

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
      - /volumes/ha/mosquitto/:/mosquitto
    deploy:
      restart_policy:
        delay: 10s
        window: 10s

networks:
  network_public:
    external: true
