version: '3.9'
services:

  homeassistant:
    image: homeassistant/home-assistant
    volumes:
      - /volumes/ha/hass/:/config
      - /mnt/media/:/mnt/media
    environment:
      - TZ=Europe/London
    deploy:
      restart_policy:
        delay: 10s
        window: 10s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.homeassistant.rule=Host(`ha.adam-ant.co.uk`)"
        - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
        - "homepage.name=Home Assistant"
        - "homepage.group=Automation"
        - "homepage.description=Home Automation controller"
        - "homepage.icon=si-homeassistant"
        - "homepage.href=https://ha.adam-ant.co.uk"
    networks:
      - default
      - network_public

  zigbee2mqtt:
    environment:
      - TZ=Europe/London
    image: koenkk/zigbee2mqtt
    deploy:
      restart_policy:
        delay: 10s
        window: 10s
        - "homepage.name=Zigbee2MQTT"
        - "homepage.group=Automation"
        - "homepage.description=Zigbee gateway & controller"
        - "homepage.icon=si-zigbee"
        - "homepage.href=http://DockerSwarm:8080"
    ports:
      - 8080:8080
    volumes:
      - /volumes/ha/zigbee/:/app/data

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
      - /volumes/ha/mosquitto/:/mosquitto
    deploy:
      restart_policy:
        delay: 10s
        window: 10s

  piper:
    image: rhasspy/wyoming-piper
    command: --voice en-gb-southern_english_female-low
    deploy:
      restart_policy:
        delay: 10s
        window: 10s
    volumes:
      - /volumes/ha/piper:/data

  whisper:
    image: rhasspy/wyoming-whisper
    command: --language en --model small-int8
    deploy:
      restart_policy:
        delay: 10s
        window: 10s
    volumes:
      - /volumes/ha/whisper:/data

networks:
  network_public:
    external: true
